<?php

echo "<div style=\"height:60px\"></div>\r\n<div id=\"add_user_form\" style=\"display:none\">\r\n  <form action=\"";
echo url("admin/user.add_post");
echo "\" id=\"form_v\" method=\"post\">\r\n    <div class=\"txt-fld\">\r\n      <label for=\"\" class=\"tit\">用户角色</label>\r\n      <input type=\"radio\" name=\"type\" value=\"1\"  checked=\"checked\">\r\n      网站主\r\n      <input type=\"radio\" name=\"type\" value=\"2\" >\r\n      广告商\r\n      <input type=\"radio\" name=\"type\" value=\"3\" >\r\n      联盟客服\r\n      <input type=\"radio\" name=\"type\" value=\"4\" >\r\n      联盟商务 </div>\r\n    <div class=\"txt-fld\">\r\n      <label for=\"\"  class=\"tit\">用户名</label>\r\n      <input id=\"username_ajax\" name=\"username\" type=\"text\">\r\n    </div>\r\n    <div class=\"txt-fld\">\r\n      <label for=\"\"  class=\"tit\">用户密码</label>\r\n      <input id=\"\" name=\"password\" type=\"text\">\r\n    </div>\r\n\t\r\n\t \r\n\t\r\n    <div class=\"txt-fld\">\r\n      <label for=\"\"  class=\"tit\">联系人</label>\r\n      <input id=\"\" name=\"contact\" type=\"text\">\r\n    </div>\r\n    <div class=\"txt-fld\">\r\n      <label for=\"\"  class=\"tit\">QQ</label>\r\n      <input id=\"\" name=\"qq\" type=\"text\">\r\n    </div>\r\n    <div class=\"btn-fld\">\r\n      <button type=\"submit\">提交 »</button>\r\n    </div>\r\n  </form>\r\n</div>\r\n<a href=\"javascript:void(0)\" class=\"sidebar_switch on_switch\" title=\"隐藏左侧\">隐藏</a>\r\n<script language=\"JavaScript\" type=\"text/javascript\">\r\n\r\n\r\n \r\n \r\n//导航子菜单\t\t\t\r\n\t\t\t\r\n \r\n$('.dropdown').on('mouseenter', function(option) { \r\n\t$('.dropdown-menu,.tpm').css('display','none'); \r\n\t$(this).find('.dropdown-menu,.tpm').css('display','block');\r\n});\r\n\r\n$('.dropdown-menu').on('mouseleave', function(option) { \r\n\t$('.dropdown-menu,.tpm').css('display','none'); \r\n});\r\n\r\n\r\n\r\n//导航菜单点其它关闭\t\t\t\r\n$('body').click(function(evt) {\r\n \t\t$('.alert').hide(\"slow\");\r\n\t\tif($(evt.target).parents(\".nav_m\").length==0){\r\n \t\t\t$('.dropdown-menu,.tpm').css('display','none'); \r\n\t\t}\r\n\t\t//$(\".popover\").css('top','-1000px'); \r\n});\r\n\t\r\n\r\n\r\nfunction err(text){\r\n\tvar h = '<div class=\"alert err\"><!-- <a class=\"close\" href=\"javascript:;\">×</a>--><strong>'+text+'.</strong> </div>';\r\n\t $(\"body\").append(h);\r\n}\r\n\r\n$(\".add_user\").click(function(){\r\n\tbox.form(\"#add_user_form\",\"新建用户\");\r\n\tremote_url = \"";
echo url("admin/user.remote_user");
echo "\";\r\n\tadd_user_vlt.init();\r\n});\r\n\r\n$(\".on_switch\").click(function(){\r\n\t if($(\"#sidebar\").is(\":hidden\")){\r\n\t\t$(\"#sidebar\").show();\r\n\t \t$('#main-content').css('marginLeft', '230px');\r\n\t \t$(\"body\").css(\"backgroundImage\",\"url('";
echo SRC_TPL_DIR;
echo "/images/main_bg.gif')\");\r\n\t \t$(this).css('left', '180px');\r\n\t }else{\r\n\t \t$(\"#sidebar\").hide();\r\n\t \t$('#main-content').css('marginLeft', '30px');\r\n\t \t$(\"body\").css(\"backgroundImage\",\"url('')\");\r\n\t \t$(this).css('left', '5px');\r\n\t }\r\n});\r\n\r\n\r\n</script>\r\n\r\n\r\n\r\n";
zy_updata();

?>
