<?php

if (!defined('IS_INSTALL')) {
	exit();
}

require_once tpl . '/header.php';
echo "<script type=\"text/javascript\" src=\"../js/jquery/js/jquery-1.7.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"../js/jquery/lib/jquery-validation/jquery.validate.js\"></script>\r\n  <div class=\"step\">\r\n    <ul>\r\n      <li class=\"on\"><em>1</em>检测环境</li>\r\n      <li class=\"current\"><em>2</em>登陆帐号</li>\r\n      <li class=\"\"><em>3</em>创建数据</li>\r\n      <li><em>4</em>完成安装</li>\r\n    </ul>\r\n  </div>\r\n  <div class=\"server\">\r\n  <form action=\"\" method=\"post\" id=\"form_b\">\r\n    <h3>您已经有一个Zyiis.com帐户？ <span class=\"mgs_text\">";
echo $db_error;
echo "</span></h3>\r\n    <table width=\"100%\" style=\"margin-top:30px\">\r\n      <tbody>\r\n        <tr>\r\n          <td width=\"160\" height=\"40\">zyiis.com 用户名*</td>\r\n          <td><input name=\"username\" type=\"text\" class=\"input_text\" id=\"username\" ></td>\r\n        </tr> \r\n        <tr>\r\n          <td height=\"40\">密码*</td>\r\n          <td><input name=\"passwds\" type=\"password\" class=\"input_text\" id=\"passwds\" ></td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"40\">验证码*</td>\r\n          <td><input name=\"imgcode\" type=\"text\" class=\"input_text\" id=\"imgcode\" >\r\n          <img src=\"http://login.sohu.com/index.php?action=imgcode\"  style=\"vertical-align:middle\"/></td>\r\n        </tr>\r\n        \r\n        \r\n        \r\n      </tbody>\r\n    </table>\r\n    \r\n \r\n    \r\n    <div class=\"bottom \">   \r\n      <input class=\"btn\" name=\"\" type=\"button\" value=\"登入\" id=\"postlogin\">   \r\n      <a href=\"http://login.sohu.com/\" target=\"_blank\" class=\"btn\">我要注册</a> </div>\r\n  \r\n  </form>\r\n</div>\r\n</div>\r\n<script>\r\n \$(\"#form_b\").validate({\r\n\t\t    errorClass :\"error\", \r\n\t\t\thighlight: function(element) {\r\n\t\t\t\t\t\$(element).closest('td').addClass(\"f_error\");\r\n\t\t\t\t},\r\n\t\t\tunhighlight: function(element) {\r\n\t\t\t\t\$(element).closest('td').removeClass(\"f_error\");\r\n\t\t\t},\r\n\t\t\trules: {\r\n                  username: {\r\n\t\t\t\t   \trequired: true \r\n                   }, \r\n\t\t\t\t  passwds: {\r\n\t\t\t\t   \trequired: true \r\n                   }, \r\n\t\t\t\t imgcode: {\r\n\t\t\t\t   \trequired: true \r\n                 } \r\n\t\t\t\t },\r\n\t\t\tmessages: {\r\n\t\t\t\tusername:\"用户名不能为空\" ,\r\n\t\t \t\tpasswds:\"密码不能为空\" ,\r\n\t\t\t\timgcode:\"验证码不能为空\" \r\n\t\t\t\t \r\n\t\t\t},\r\n\t \r\n\t\t\terrorElement: 'span',\r\n\t\t\t \r\n        });\r\n\r\nfunction b(){}\r\n\$(\"#postlogin\").click(function(){ \r\n\tif(!\$(\"#form_b\").valid()){\r\n\t\treturn false;\r\n\t} \r\n\tvar passwds = \$(\"#passwds\").val();\r\n\tvar imgcode = \$(\"#imgcode\").val();\r\n\tvar username = \$(\"#username\").val();\r\n\t\$.ajax({\r\n\t\ttype : \"get\",\r\n\t\tasync:false,\r\n\t\turl : \"http://login.sohu.com/?action=InstallLogin\",\r\n\t\tdata: \"username=\"+username+\"&passwds=\"+passwds+\"&imgcode=\"+imgcode,\r\n\t\tdataType : \"jsonp\",\r\n\t\tjsonp: \"a\",//服务端用于接收callback调用的function名的参数\r\n    \tjsonpCallback:\"b\",//callback的function名称\r\n\t\tsuccess : function(json){\r\n\t\t\t var msg = json.msg;\r\n\t\t\t if(msg=='ok'){\r\n\t\t\t \twindow.location.href=\"index.php?action=db&s=\"+json.s;\r\n\t\t\t }\r\n\t\t\t \r\n\t\t\t \$(\".mgs_text\").show().html(json.msg);\r\n\t\t},\r\n\t\terror:function(json){\r\n\t\t\t  \$(\".mgs_text\").html(\"登入失败，请重新登入\");\r\n\t\t}\r\n\t});\r\n});\r\n\t\t\r\n</script>\r\n\r\n";
require_once tpl . '/footer.php';

?>
